### ISSUE TITLE
Magento 2 version?

### ISSUE THREAD

**Issue by designbyadrian** [obukhow/AdaptiveResize#12]
I apologise for spamming your issue tracker, but do you have plans for a M2 version of this extension?

**Comment by obukhow** [comment]
Hi! I don't have any plans do create M2 version of the plugin for now. Not even sure  does M2 have adaptive resize or not.

**Comment by designbyadrian** [comment]
Thanks for your reply. M2 doesn't have adaptive resize. It does
provide and XML file in which you can configure and add image sizes,
so it's not too hard to add your img srcset code yourself. But M2
can't crop images, and that's the issue I'm facing! I ended up my
passing the entire thing and crop images on S3 using imgix.com.

**Comment by chombe** [comment]
Hi there,

Since you don't have plan for M2 version we adopted this version for M2.
You can find it [here](https://packagist.org/packages/trive/module-adaptive-resize)
and [here](https://github.com/trive-digital/AdaptiveResizeM2)

Regards

**Comment by obukhow** [comment]
Great! I'll add a link to your repo in readme.md

**Comment by obukhow** [comment]
Added link in readme.md
