### ISSUE TITLE
Usage outside product page

### ISSUE THREAD

**Issue by flakerimi** [obukhow/AdaptiveResize#3]
Does this work for custom module, like giving the path of image and adaptive resize it. If so how it works.

Maybe integrate this : http://subesh.com.np/2009/11/image-resize-magento-cache-resized-image/

**Comment by kaptenw** [comment]
I'm actually experiencing the same issue as @flakerimi did. The cropping works but it returns a place holder image instead of the actual image when trying to crop an image located in the media folder. I don't feel like modifying any core files. I'll continue my search...
